agencies:
  - Bluethink
  - Extia
  - Alten
  - Akkodis
  - Expleo
  - Devoteam
  - Inetum
  - CGI
  - Capgemini
  - Sopra Steria
  - Atos
  - Randstad
  - Hays
  - Michael Page
  - Robert Half
  - Fed IT
  - Approach People
  - Manpower
  - Adecco
  - Proman
  - Synergie
  - Groupe Actual
